### ISSUE TITLE
Error with CSV to SObject Action

### ISSUE THREAD

**Issue by ericrsmith35** [forcePanda/Flow-Repo#1]
I'm trying to use this action in a Flow and I keep getting this error message:

The "Load_CSV_Records" element in your flow has validation errors.

**Comment by forcePanda** [comment]
Seems to be working fine in my org. Also tried it in a fresh org, same result.
Can you please share the steps(or some screenshots) about how you have set it up?

**Comment by ericrsmith35** [comment]
I did not have all of the column names correct - I have it working now.  Have you had issues in the past geting Datetime fields to load correctly from an Excel CSV?

**Comment by forcePanda** [comment]
I never tested it with Datetime(because I forgot🙈) so I'm not sure if the current action can handle it.
