### ISSUE TITLE
[Question] use of output variables from subflow?

### ISSUE THREAD

**Issue by erezerezg** [forcePanda/Flow-Repo#2]
The README mentions setting Input/Output variables, but only accepts declaration of inputs. Could this component be used to provide an output as well?

**Comment by forcePanda** [comment]
Hi,

Are you talking about the 'Call Subflow' apex action?

**Comment by erezerezg** [comment]
Yes, apologies for not mentioning that specifically, got here directly from the blog post.

**Comment by forcePanda** [comment]
Ahh. Great question!
Unfortunately, my action doesn't support it.
