### ISSUE TITLE
Partner Community Requirement

### ISSUE THREAD

**Issue by jncart** [forcePanda/Flow-Repo#4]
The Test Class references IsPartner on Account, which is a field that only exists in an org with a Partner Community. The package will fail to deploy to an org that does not have a Partner Community.

**Comment by forcePanda** [comment]
Can you add a reference to the action this issue is related to?

**Comment by jncart** [comment]
Dynamic Field Value from SObject Record

**Comment by forcePanda** [comment]
Ah yes!
I'll try and fix it soon. 

Thank you for noticing! :)

**Comment by forcePanda** [comment]
Added the fix.
https://github.com/forcePanda/Flow-Repo/blob/master/Apex%20Actions/Dynamic%20Field%20Value%20from%20SObject%20Record/README.md
